version: '3.7'
services:
  elcocinero:
    restart: always
    container_name: moments
    image: elcocinero:latest
    environment:
      - DATABASE_URL=mysql://root:my-secret-pw@mysql:3306/elcocinero
      - HOST=0.0.0.0
      - PORT=5001
    ports:
      - 5001:5001
  mysql:
    restart: always
    container_name: mariadb
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=elcocinero
    ports:
      - 3306:3306